language: cpp
sudo: false
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz doxygen

script:
  - make unit-test/test_all
  - make examples/helloworld
  - make examples/counterwithreset
  - make examples/trivialvendingmachine
  - make examples/fancyvendingmachine
  - make examples/beatmachine
  - make docs

