language: cpp
sudo: false
compiler:
  - clang
  - gcc

script:
  - make unit-test/test_all
  - make examples/helloworld
  - make examples/counterwithreset
  - make examples/trivialvendingmachine
  - make examples/portuguesetranslator
  - make examples/fancyvendingmachine
  - make examples/beatmachine

